### ISSUE TITLE
Support for partial citation links

### ISSUE THREAD

**Issue by joezhouchenye** [bcdavasconcelos/cite-field#1]
![image](https://user-images.githubusercontent.com/59191277/225540562-a186666a-b55c-4d2c-8537-de766fab5494.png)

It would be great to add a feature that only links with the year field and keeps the other parts.

**Comment by bcdavasconcelos** [comment]
Could you provide a minimal example and explain what it is that you expect should happen and that currently does not happen?

**Comment by bcdavasconcelos** [comment]
I just pushed some changes and you can use an extra dot to avoid creating a link. E.g. `[@Citekey]{.author.}`. Is this what you needed?

**Comment by joezhouchenye** [comment]
Unfortunately, not. Maybe it's a `citeproc` related issue.

I have seen this issue https://github.com/jgm/pandoc-citeproc/issues/268 in the archived `pandoc-citeproc` repository. Some people want to link/color the entire citation, not only the year. Maybe that's why this feature is changed in `citeproc`. As the repository is archived, I am unable to discuss this issue there.

I am using the Chicago Manual of Style 17th edition (author-date) csl style from Zotero.

Using syntax `[@stairs2002]`, it will give me this result:

![image](https://user-images.githubusercontent.com/59191277/225831527-426fef95-ac13-48a9-9bee-5181a83732e2.png)

Using syntax `@stairs2022`, it will give me this result:

![image](https://user-images.githubusercontent.com/59191277/225831677-501d1808-64a2-4823-847e-e497f47ffc78.png)

What I want is to have "Stairs" in normal text mode and "2002" is a hyperlink to the reference in "(Stairs 2002)".

**Comment by bcdavasconcelos** [comment]
I am closing this, since its [duplicated](https://github.com/jgm/citeproc/issues/129) and unrelated to `citefield` filter.
