### ISSUE TITLE
Include non-dropping-particle in family name

### ISSUE THREAD

**Issue by mxpiotrowski** [bcdavasconcelos/cite-field#3]
Hi,

Thanks for this great filter!

Currently, `.author` is filled from the `family` field only, which means that non-dropping particles are dropped.  I would suggest to replace line 99 by something like:

``` lua
local prefix = ref[the_arg][ordinal]["non-dropping-particle"] or nil
if prefix then prefix = prefix .. " " end
the_result = (prefix or "") .. ref[the_arg][ordinal]["family"]
```

What do you think?

Best regards,
Michael

**Comment by bcdavasconcelos** [comment]
Thanks for the suggestion, @mxpiotrowski! I committed this change to the main branch :-)

**Comment by mxpiotrowski** [comment]
Awesome, thanks for the quick and positive response!
